// สร้างเลขเวอร์ชัน git สำหรับหน้า Home (รันอัตโนมัติก่อน build ผ่าน npm `prebuild`)
// เขียน short SHA ของคอมมิตที่กำลัง build ลง src/lib/gitVersion.ts
// → build บน Render จะได้ SHA ของโค้ดที่ deploy จริง (static export อ่าน git ตอน runtime ไม่ได้)
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

let sha = "dev";
try {
  sha = execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim().slice(0, 7) || "dev";
} catch {
  // ไม่มี git (เช่นดึงมาเป็น zip) — ใช้ค่าเดิมถ้ามีไฟล์อยู่แล้ว
  try {
    const prev = fs.readFileSync(path.join(__dirname, "..", "src", "lib", "gitVersion.ts"), "utf8");
    const m = prev.match(/GIT_SHA\s*=\s*"([^"]+)"/);
    if (m) sha = m[1];
  } catch {
    /* คง dev */
  }
}

const out = path.join(__dirname, "..", "src", "lib", "gitVersion.ts");
fs.writeFileSync(
  out,
  `// auto-generated by scripts/write-version.js (npm prebuild) — ห้ามแก้เอง\n` +
    `// = short SHA ของคอมมิตที่ build (หน้า Home แสดงท้ายหน้าแบบจาง ๆ)\n` +
    `export const GIT_SHA = ${JSON.stringify(sha)};\n`,
);
console.log(`[version] GIT_SHA=${sha}`);
