// Writes the short git SHA being built into src/lib/gitVersion.ts.
// Runs via npm `prebuild`/`predev`. On Render the build runs at the deployed
// commit, so the static export bakes in the deployed SHA (static export cannot
// read git at runtime). English-only comments: keeps the generated file
// encoding-safe across consoles.
const { execSync } = require("child_process");
const fs = require("fs");
const path = require("path");

let sha = "dev";
try {
  sha = execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim().slice(0, 7) || "dev";
} catch {
  // No git (e.g. zip download) — reuse previous value when present.
  try {
    const prev = fs.readFileSync(path.join(__dirname, "..", "src", "lib", "gitVersion.ts"), "utf8");
    const m = prev.match(/GIT_SHA\s*=\s*"([^"]+)"/);
    if (m) sha = m[1];
  } catch {
    /* keep dev */
  }
}

const out = path.join(__dirname, "..", "src", "lib", "gitVersion.ts");
fs.writeFileSync(
  out,
  `// auto-generated by scripts/write-version.js (npm prebuild/predev) - do not edit\n` +
    `// short SHA of the commit being built (home page shows it faintly at the bottom)\n` +
    `export const GIT_SHA = ${JSON.stringify(sha)};\n`,
  "utf8",
);
console.log(`[version] GIT_SHA=${sha}`);
