-- 042_push_subscriptions.sql
--
-- Web Push (VAPID) — แจ้งเตือนเข้า notification tray ของมือถือ/เดสก์ท็อป
-- ผ่านเบราว์เซอร์ โดยไม่ต้องอาศัย LINE (ยังคงส่ง LINE คู่กันไปด้วย)
--
-- ทำไมต้องมีตารางนี้: Web Push ต้องเก็บ endpoint + กุญแจเข้ารหัสของ "แต่ละ
-- อุปกรณ์" (1 เบราว์เซอร์ = 1 row) แล้วฝั่งเซิร์ฟเวอร์ส่งซ้ำทุกครั้งที่เกิด
-- alert — เก็บใน localStorage ไม่ได้เพราะคนละเครื่อง/คนละเบราว์เซอร์
--
-- ⚠️ user_id เป็น TEXT ไม่ใช่ uuid — บทเรียนจาก 022_line_notify_fix.sql:
--    แอปรันด้วย pseudo-user "demo" ซึ่ง cast เป็น uuid ไม่ผ่าน ⇒ insert 400
--    แล้ว Database.insert กลืน error ทิ้ง (เงียบ ไม่มีแถวเลย)
--
-- ⚠️ endpoint/p256dh/auth = ข้อมูลอ่อนไหว (ใครได้ไป = ส่ง push หาเจ้าของได้)
--    ⇒ RLS เปิด และ **ไม่สร้าง policy ให้ anon/authenticated** ให้ service_role
--    เท่านั้น (frontend ไม่เคยอ่านตารางนี้ตรง ๆ — อ่านผ่าน API ที่นับจำนวน)
--
-- อ่าน/เขียนโดย: app/integrations/web_push.py (ส่ง)
--                app/api/routes/push.py (ลงทะเบียน/ยกเลิก/ทดสอบ)
--
-- Idempotent: รันซ้ำได้ ไม่ error

create table if not exists push_subscriptions (
    id          bigint generated by default as identity primary key,
    -- URL ของ push service (FCM/Mozilla/APNs) — 1 อุปกรณ์ = 1 endpoint
    endpoint    text not null unique,
    p256dh      text not null,          -- กุญแจสาธารณะของเบราว์เซอร์ (base64url)
    auth        text not null,          -- auth secret ของเบราว์เซอร์ (base64url)
    user_agent  text,                   -- ไว้แยกแยะว่าอุปกรณ์ไหนคือเครื่องไหน
    user_id     text,                   -- "demo" (ไม่ใช่ uuid — ดูหมายเหตุข้างบน)
    enabled     boolean not null default true,
    -- จำนวนครั้งที่ส่งไม่สำเร็จติดกัน — ใช้ปิด row ที่ตายแล้วโดยไม่ต้องลบ
    fail_count  integer not null default 0,
    last_error  text,
    last_ok_at  timestamptz,
    created_at  timestamptz not null default now()
);

create index if not exists push_subscriptions_enabled_idx
    on push_subscriptions (enabled);

alter table push_subscriptions enable row level security;

-- service_role (backend) เท่านั้น — ไม่มี policy สำหรับ anon โดยเจตนา
drop policy if exists push_subscriptions_service_all on push_subscriptions;
create policy push_subscriptions_service_all on push_subscriptions
    for all to service_role using (true) with check (true);

comment on table push_subscriptions is
    'Web Push (VAPID) subscriptions — 1 แถว = 1 อุปกรณ์/เบราว์เซอร์ที่กด "เปิดการแจ้งเตือน" ในหน้า Settings';

comment on column push_subscriptions.endpoint is
    'push service endpoint ของอุปกรณ์ (FCM/Mozilla/APNs) — ข้อมูลอ่อนไหว ห้ามเปิดให้ anon อ่าน';

comment on column push_subscriptions.enabled is
    'false = ปิด/ตายแล้ว (ผู้ใช้กดปิดเอง หรือ push service ตอบ 404/410 = endpoint หมดอายุ)';

comment on column push_subscriptions.fail_count is
    'ส่งไม่สำเร็จติดกันกี่ครั้ง — ถึงเพดานใน web_push.MAX_FAILS แล้วระบบจะ set enabled=false ให้เอง';
