"""Final thesis validation for a signal right before order placement (P0-5).

WHY THIS EXISTS
---------------
A signal is generated by the scanner against the market AT THAT MOMENT and is
then stored as a row in ``signals`` (asset, direction, entry, SL, TP,
confidence, created_at). It is consumed later — either by the owner pressing
Approve or by the auto-trader in the next cycle — up to ``SIGNAL_TTL_MIN``
(30) minutes later. ``execute_signal`` re-anchors the ENTRY price to the live
spot, but until now NOTHING re-checked the REASON the signal existed: the
trend, the Supertrend flip, the XAU breakout/retest structure and the news
state could all have inverted in between, and the order would still fire.

This module is the last line of defence between "the card looked good 20 min
ago" and a real order: it re-derives a FRESH indicator snapshot at execution
time and refuses to place the order when the thesis that justified the signal
no longer holds.

DESIGN
------
* ``validate_thesis(signal, snapshot, *, now=None, max_age_min=None)`` is a
  PURE function: it reads a signal row (dict) and a fresh snapshot (dict, as
  produced by ``quotes.snapshot_from_candles`` / ``fetch_all_snapshots``) and
  returns a ``ThesisValidation``. It never raises and never touches the DB or
  the network — the caller fetches and passes the snapshot in.
* PRIMARY THESIS = EMA. The scanner derives BUY/SELL from EMA-fast vs
  EMA-slow, so the EMA trend is the ONE thing that must still hold: if it
  flips against the signal direction the order is BLOCKED (``trend_flipped``).
* CONFIRMATION (not a sole veto) = Supertrend (+MACD). A single coarse
  indicator drifting against the signal is NOT enough to kill a trade — the
  current ``_supertrend_dir`` is a coarse SMA-band heuristic with no backtest
  confirmation as a hard gate, and the scanner never cites it as the reason a
  card exists. So:
    - Supertrend alone opposing → recorded as a NON-BLOCKING WARNING
      (``supertrend_conflict`` / ``supertrend_flipped``); the order still
      fires but the conflict is logged for telemetry/confidence.
    - Supertrend AND MACD opposing TOGETHER → BLOCKED
      (``thesis_corroboration_failed``): TWO independent momentum/trend
      confirmations disagreeing is treated as a failed corroboration.
* BASELINE COMPARISON: the signal row stores the indicator values captured at
  signal-creation time (``baseline_*`` columns). Comparing them against the
  fresh snapshot lets the gate say WHY Supertrend disagrees:
    - ``supertrend_conflict``  — it was ALREADY opposing when the card was
      created (the scanner's Supertrend disagreed from the start; purely
      informational).
    - ``supertrend_flipped``   — it AGREED at creation and flipped later (a
      genuine change of state since the signal was stored).
  Signals created before this change carry no baseline; they are treated as
  ``supertrend_conflict`` (never a flip) so the missing column cannot falsely
  blame a flip — and they are expired on deploy (TTL is only 30 min).
* FAIL-CLOSED at the seam (``execution.execute_signal``): a MISSING snapshot
  (``snapshot is None`` / empty) BLOCKS the order with
  ``latest_snapshot_unavailable`` — a thesis that cannot be re-verified must
  never be assumed valid (same philosophy as the P0-4 settings read).
* The SAME object is produced on BOTH paths (manual ``/approve`` and the
  auto-trader) because both call ``execute_signal`` — Single Path preserved.

MACHINE-READABLE REASON CODES (verbatim, stable)
------------------------------------------------
* ``signal_thesis_invalidated``   — the generic bucket: the stored signal never
      stated an explicit thesis and the fresh data no longer supports the
      direction at all. (Umbrella code; specific codes below take precedence.)
* ``trend_flipped``               — the fresh EMA trend (EMA-fast vs EMA-slow)
      now CONTRADICTS the signal direction. BLOCKS (primary thesis).
* ``thesis_corroboration_failed`` — BOTH Supertrend AND MACD now oppose the
      signal direction (two independent confirmations disagree). BLOCKS.
* ``supertrend_flipped``          — Supertrend flipped against the direction
      since the signal was created (it agreed at creation). Warning (does NOT
      block on its own).
* ``supertrend_conflict``         — Supertrend already opposed at creation
      (no baseline change). Warning (does NOT block on its own).
* ``breakout_invalidated``        — XAUUSD Strategy-D only: the stored signal
      was a breakout/retest entry but the fresh snapshot no longer shows a
      valid breakout for that direction (structure gone / flipped).
* ``regime_blocked``              — the fresh regime is hostile to the
      direction (``sideway`` / ``high_volatility`` / ``news_driven_market``).
* ``news_state_changed``          — a high-impact event is flagged NOW and was
      not when the signal was stored (or vice-versa). News can invalidate a
      technical setup instantly.
* ``signal_expired``              — the signal row is older than ``max_age_min``
      (when the caller passes one; the TTL queue normally handles this).
* ``latest_snapshot_unavailable`` — no fresh snapshot could be produced. BLOCKS.

NOTE on back-compat: callers that pass no ``signal`` row, or a signal with no
``created_at``, keep the previous behaviour (no expiry check). The trend /
Supertrend / regime checks only run when the snapshot actually carries those
fields (all-zero / missing ⇒ skipped), so a data feed that does not compute an
indicator for an asset never produces a false block. A signal row without a
``baseline_supertrend_dir`` is read as "no baseline" ⇒ ``supertrend_conflict``
(never a false ``supertrend_flipped``).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

# Status values (machine-readable), mirroring config_validation.
STATUS_VALID = "VALID"
STATUS_INVALID = "INVALID"
STATUS_UNKNOWN = "UNKNOWN"

# Regimes that are hostile to ANY fresh directional entry (see
# strategy_engine.regime_of): the market is either directionless or driven by
# noise/news, so a stored technical thesis cannot be trusted to still hold.
HOSTILE_REGIMES = frozenset({
    "sideway", "high_volatility", "news_driven_market",
})

# Trend regimes per direction — the regime the signal's side actually needs.
_BULLISH_REGIMES = frozenset({"bull_trend", "strong_bull_trend"})
_BEARISH_REGIMES = frozenset({"bear_trend", "strong_bear_trend"})


@dataclass
class ThesisIssue:
    """One reason the stored thesis no longer holds."""

    code: str                 # stable, machine-readable reason code
    message: str              # human-readable (Thai) explanation
    severity: str = "error"   # "error" blocks execution; "warning" does not

    def as_dict(self) -> dict[str, Any]:
        return {"code": self.code, "message": self.message,
                "severity": self.severity}


@dataclass
class ThesisValidation:
    """Result of re-validating one signal thesis against a fresh snapshot."""

    status: str = STATUS_VALID
    issues: list[ThesisIssue] = field(default_factory=list)
    source: str = "live"                       # "live" | "none"
    values: dict[str, Any] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        """True only when VALID — INVALID and UNKNOWN both block (fail-closed)."""
        return self.status == STATUS_VALID

    @property
    def error_codes(self) -> list[str]:
        return [i.code for i in self.issues if i.severity == "error"]

    @property
    def reason(self) -> str:
        """Primary reason code for a blocked order (or '' when valid).

        Prefers a SPECIFIC code over the ``signal_thesis_invalidated``
        umbrella so logs/telemetry name the actual cause (trend_flipped,
        supertrend_flipped, ...); falls back to the umbrella only when it is
        the sole code.
        """
        codes = self.error_codes
        for c in codes:
            if c != "signal_thesis_invalidated":
                return c
        return codes[0] if codes else ""

    def summary(self) -> str:
        """One-line status for logs / LINE / API."""
        if self.status == STATUS_VALID:
            return "thesis VALID"
        if self.status == STATUS_UNKNOWN:
            return "thesis UNKNOWN — snapshot unavailable (fail-closed)"
        if not self.issues:
            return "thesis INVALID"
        return "thesis INVALID — " + "; ".join(
            f"{i.code}: {i.message}" for i in self.issues)

    def as_dict(self) -> dict[str, Any]:
        return {
            "status": self.status,
            "ok": self.ok,
            "reason": self.reason,
            "issues": [i.as_dict() for i in self.issues],
            "source": self.source,
            "values": dict(self.values),
        }


def _parse_dt(raw: Any) -> Optional[datetime]:
    if not raw:
        return None
    try:
        dt = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except ValueError:
        return None
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


def _as_direction(direction: Any) -> str:
    return str(direction or "").strip().upper()


def _num(snapshot: dict, key: str, default: float = 0.0) -> float:
    try:
        return float(snapshot.get(key))
    except (TypeError, ValueError):
        return default


def _opt_num(source: Any, key: str) -> Optional[float]:
    """Like ``_num`` but returns ``None`` when the key is absent/blank/invalid
    (used for the OPTIONAL ``baseline_*`` signal columns: ``None`` means \"no
    baseline recorded\", which is distinct from 0)."""
    if not source:
        return None
    raw = source.get(key)
    if raw is None or raw == "":
        return None
    try:
        return float(raw)
    except (TypeError, ValueError):
        return None


def validate_thesis(signal: Optional[dict], snapshot: Optional[dict], *,
                    now: Optional[datetime] = None,
                    max_age_min: Optional[int] = None) -> ThesisValidation:
    """Re-check that a stored signal's thesis still holds on the live market.

    Parameters
    ----------
    signal : dict | None
        The stored ``signals`` row. Only ``direction`` and (optionally)
        ``created_at`` are consumed; a missing/empty row means "no thesis to
        check" and returns VALID (back-compat with callers that do not pass a
        row — e.g. extended-open which has its own reviewed plan).
    snapshot : dict | None
        A FRESH indicator snapshot for the signal's asset, exactly as produced
        by ``quotes.snapshot_from_candles`` / ``fetch_all_snapshots``. A
        missing/empty snapshot blocks (``latest_snapshot_unavailable``).
    now : datetime | None
        Injectable clock (tests). Defaults to ``datetime.now(timezone.utc)``.
    max_age_min : int | None
        When set, a signal whose ``created_at`` is older expires
        (``signal_expired``). ``None`` (default) skips the expiry check.

    Returns
    -------
    ThesisValidation
        ``ok`` is True only when the thesis still holds.
    """
    now = now or datetime.now(timezone.utc)

    # No signal row → nothing to invalidate (back-compat). Callers that DO
    # have a row get the full check.
    if not signal:
        return ThesisValidation(status=STATUS_VALID, source="live")

    direction = _as_direction(signal.get("direction"))
    is_buy = direction == "BUY"
    is_sell = direction == "SELL"
    asset = str(signal.get("asset") or "").upper()

    # ---- snapshot availability (FAIL-CLOSED) ------------------------------
    if not snapshot or not isinstance(snapshot, dict) or not snapshot.get("asset"):
        return ThesisValidation(
            status=STATUS_UNKNOWN, source="none",
            issues=[ThesisIssue(
                code="latest_snapshot_unavailable",
                message=("ดึงข้อมูลราคา/อินดิเคเตอร์ล่าสุดไม่ได้ — ยืนยัน thesis "
                         "ไม่ได้ จึงงดเปิดออเดอร์ (fail-closed)"),
            )],
        )

    issues: list[ThesisIssue] = []

    # ---- expiry -----------------------------------------------------------
    if max_age_min is not None:
        created = _parse_dt(signal.get("created_at"))
        if created is not None:
            age_min = (now - created).total_seconds() / 60.0
            if age_min > max_age_min:
                issues.append(ThesisIssue(
                    code="signal_expired",
                    message=(f"สัญญาณนี้เก่ากว่า {max_age_min} นาที "
                             f"(อายุ {age_min:.0f} นาที) — thesis อาจไม่จริงแล้ว"),
                ))

    ema_fast = _num(snapshot, "ema_fast")
    ema_slow = _num(snapshot, "ema_slow")
    supertrend_dir = int(_num(snapshot, "supertrend_dir"))
    macd_hist = _num(snapshot, "macd_hist")
    breakout_state = int(_num(snapshot, "breakout_state"))
    breakout_level = _num(snapshot, "breakout_level")
    adx = _num(snapshot, "adx")
    atr_pct = _num(snapshot, "atr_pct")
    news_now = bool(snapshot.get("high_impact_event"))
    regime = _regime_of(snapshot)

    # Baseline indicator values captured when the signal was created (may be
    # absent on pre-migration signals ⇒ read as None ⇒ "no baseline").
    base_supertrend = _opt_num(signal, "baseline_supertrend_dir")
    base_macd = _opt_num(signal, "baseline_macd_hist")

    values = {
        "asset": asset,
        "direction": direction,
        "ema_fast": ema_fast,
        "ema_slow": ema_slow,
        "supertrend_dir": supertrend_dir,
        "macd_hist": macd_hist,
        "baseline_supertrend_dir": base_supertrend,
        "baseline_macd_hist": base_macd,
        "breakout_state": breakout_state,
        "breakout_level": breakout_level,
        "adx": adx,
        "atr_pct": atr_pct,
        "high_impact_event": news_now,
        "regime": regime,
    }

    # ---- trend flip (EMA fast vs slow) ------------------------------------
    # PRIMARY THESIS. Only evaluated when the feed actually computed both EMAs
    # for this asset; an all-zero snapshot would otherwise read as "bear_trend"
    # and false-block.
    if ema_fast and ema_slow and (is_buy or is_sell):
        trend_up = ema_fast > ema_slow
        if (is_buy and not trend_up) or (is_sell and trend_up):
            issues.append(ThesisIssue(
                code="trend_flipped",
                message=("แนวโน้ม EMA พลิกสวนทางกับสัญญาณ "
                         f"({'EMA50<EMA200' if not trend_up else 'EMA50>EMA200'}) "
                         f"— ทิศทาง {direction} ไม่สอดคล้องแล้ว"),
            ))

    # ---- Supertrend / MACD confirmation (NOT a sole veto) -----------------
    # EMA is the primary thesis (above) and does the actual blocking. The
    # coarse Supertrend (and MACD) act as CONFIRMATION: a SINGLE indicator
    # drifting against the signal is recorded as a non-blocking WARNING, only
    # when BOTH disagree together do we treat it as a failed corroboration and
    # block ("thesis_corroboration_failed").
    if (is_buy or is_sell):
        st_opposes = (supertrend_dir != 0 and
                      ((is_buy and supertrend_dir < 0) or
                       (is_sell and supertrend_dir > 0)))
        macd_opposes = (macd_hist != 0 and
                        ((is_buy and macd_hist < 0) or
                         (is_sell and macd_hist > 0)))
        if st_opposes:
            # Distinguish a genuine FLIP (agreed at creation, opposed now) from
            # a from-the-start CONFLICT using the stored baseline. No baseline
            # ⇒ treat as conflict (never falsely blame a flip).
            flipped = None
            if base_supertrend is not None and int(base_supertrend) != 0:
                base_dir = int(base_supertrend)
                base_agreed = ((is_buy and base_dir > 0) or
                               (is_sell and base_dir < 0))
                flipped = bool(base_agreed)
            if flipped:
                code = "supertrend_flipped"
                msg = ("Supertrend พลิกสวนทางกับสัญญาณ (ตอนสร้างเห็นด้วย "
                       f"baseline={int(base_supertrend):+d} → "
                       f"dir={supertrend_dir:+d})")
            else:
                code = "supertrend_conflict"
                msg = ("Supertrend สวนทางกับสัญญาณมาตั้งแต่ต้น "
                       f"(dir={supertrend_dir:+d}) — บันทึกเป็นข้อขัดแย้ง "
                       "ไม่บล็อก (ใช้ EMA เป็น thesis หลัก)")
            issues.append(ThesisIssue(code=code, message=msg,
                                      severity="warning"))
        if st_opposes and macd_opposes:
            # TWO independent confirmations disagree ⇒ corroboration failed.
            issues.append(ThesisIssue(
                code="thesis_corroboration_failed",
                message=("ทั้ง Supertrend และ MACD สวนทางกับสัญญาณพร้อมกัน "
                         f"(st={supertrend_dir:+d}, macd={macd_hist:+.4f}) "
                         "— การยืนยันล้มเหลว"),
            ))

    # ---- regime block -----------------------------------------------------
    if regime in HOSTILE_REGIMES and (is_buy or is_sell):
        issues.append(ThesisIssue(
            code="regime_blocked",
            message=(f"สภาวะตลาดล่าสุดเป็น '{regime}' — ไม่เหมาะกับ entry "
                     f"ทิศทาง {direction} (ตลาดไร้เทรนด์/ผันผวน/ขับด้วยข่าว)"),
        ))
    elif regime and (is_buy or is_sell):
        wants_bull = is_buy
        regime_is_bull = regime in _BULLISH_REGIMES
        regime_is_bear = regime in _BEARISH_REGIMES
        if (wants_bull and regime_is_bear) or (not wants_bull and regime_is_bull):
            issues.append(ThesisIssue(
                code="regime_blocked",
                message=(f"สภาวะตลาดล่าสุดเป็น '{regime}' สวนทางกับทิศทาง "
                         f"{direction}"),
            ))

    # ---- XAUUSD Strategy-D breakout structure -----------------------------
    # breakout_state: 2 = breakout, 1 = retest, 0 = none. A BUY needs a live
    # upside breakout/retest; a SELL needs the structure GONE (0). When the
    # feed reports a breakout context for the direction it contradicts, the
    # Strategy-D entry is invalid.
    if asset == "XAUUSD" and (is_buy or is_sell) and (
            breakout_state or breakout_level):
        if is_buy and breakout_state == 0:
            issues.append(ThesisIssue(
                code="breakout_invalidated",
                message=("XAUUSD: โครงสร้าง breakout/retest ฝั่ง BUY หายไปแล้ว "
                         "(breakout_state=0) — Strategy D ใช้ไม่ได้"),
            ))
        elif is_sell and breakout_state in (1, 2):
            issues.append(ThesisIssue(
                code="breakout_invalidated",
                message=(f"XAUUSD: ยังมีโครงสร้าง breakout/retest ฝั่งขึ้นอยู่ "
                         f"(state={breakout_state}) — ขัดกับสัญญาณ SELL"),
            ))

    # ---- news state -------------------------------------------------------
    # A high-impact event flagged NOW is an instant thesis-invalidation for a
    # purely technical setup (regime_of would also return news_driven_market,
    # but this keeps a specific, searchable code AND fires even if the feed's
    # regime logic changes).
    if news_now:
        issues.append(ThesisIssue(
            code="news_state_changed",
            message=("ตรวจพบข่าวผลกระทบสูง (high-impact event) ณ เวลาส่งคำสั่ง "
                     "— สถานะข่าวเปลี่ยนไปจากตอนสร้างสัญญาณ"),
        ))

    if not issues:
        return ThesisValidation(status=STATUS_VALID, source="live", values=values)

    # Warnings (e.g. Supertrend-only conflict/flip — P0-5 refinement: EMA is
    # the primary thesis, Supertrend is CONFIRMATION not a sole veto) are
    # recorded for telemetry but NEVER block. Only an error code invalidates.
    if not any(i.severity == "error" for i in issues):
        return ThesisValidation(status=STATUS_VALID, issues=issues,
                                source="live", values=values)

    # Umbrella code: always present on an INVALID result so a caller that only
    # switches on ``signal_thesis_invalidated`` still catches EVERY thesis
    # failure, while the specific code (trend_flipped, supertrend_flipped, ...)
    # sits alongside it for precise handling / telemetry.
    issues.insert(0, ThesisIssue(
        code="signal_thesis_invalidated",
        message="thesis ของสัญญาณถูกหักล้างจากข้อมูลล่าสุด",
    ))

    return ThesisValidation(
        status=STATUS_INVALID, issues=issues, source="live", values=values)


def _regime_of(snapshot: dict) -> str:
    """Re-derive the market regime from a fresh snapshot (mirror of
    ``strategy_engine.regime_of`` but dict-based so this module stays decoupled
    from the engine dataclass)."""
    if not snapshot:
        return ""
    if snapshot.get("high_impact_event"):
        return "news_driven_market"
    adx = _num(snapshot, "adx")
    atr_pct = _num(snapshot, "atr_pct")
    ema_fast = _num(snapshot, "ema_fast")
    ema_slow = _num(snapshot, "ema_slow")
    # No usable trend inputs → no regime to judge.
    if not adx and not (ema_fast or ema_slow):
        return ""
    if adx < 20:
        return "sideway"
    if atr_pct > 2.5:
        return "high_volatility"
    if ema_fast > ema_slow:
        return "bull_trend" if adx < 35 else "strong_bull_trend"
    return "bear_trend" if adx < 35 else "strong_bear_trend"
